default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: devops_bingo
  user: postgres
  password: postgres

production:
  <<: *default
  database: devops_bingo_production